import { sql } from './db';
import { scrypt as _scrypt, randomBytes, timingSafeEqual } from 'crypto';
import { promisify } from 'util';
import type { Role, Session } from './rbac';
const scrypt=promisify(_scrypt) as (p:string,s:Buffer,k:number)=>Promise<Buffer>;
export async function hashPassword(plain:string){const salt=randomBytes(16);const hash=await scrypt(plain,salt,64);return `scrypt$${salt.toString('hex')}$${hash.toString('hex')}`}
export async function verifyPassword(plain:string,stored:string){const [scheme,saltHex,hashHex]=stored.split('$');if(scheme!=='scrypt'||!saltHex||!hashHex)return false;const expected=Buffer.from(hashHex,'hex');const actual=await scrypt(plain,Buffer.from(saltHex,'hex'),expected.length);return expected.length===actual.length&&timingSafeEqual(expected,actual)}
export type StudentLoginInput={organizationCode:string;loginAlias:string;password:string};
export async function authenticateStudent(input:StudentLoginInput):Promise<{session:Session;mustRotate:boolean}|null>{const rows=await sql`SELECT sc.id,sc.student_id,sc.organization_id,sc.credential_hash,sc.must_rotate,p.display_name,p.preferred_locale,p.status AS profile_status,o.status AS org_status FROM student_credentials sc JOIN profiles p ON p.id=sc.student_id JOIN organizations o ON o.id=sc.organization_id WHERE lower(sc.login_alias)=lower(${input.loginAlias}) AND lower(o.semantic_id)=lower(${input.organizationCode}) LIMIT 1`;const row=rows[0];if(!row){await hashPassword(input.password);return null}if(row.profile_status!=='active'||row.org_status!=='active')return null;if(!await verifyPassword(input.password,row.credential_hash))return null;return {session:{profileId:row.student_id,role:'student' as Role,organizationId:row.organization_id,displayName:row.display_name,locale:row.preferred_locale==='en'?'en':'vi'},mustRotate:row.must_rotate}}
export async function issueStudentCredential(p:{studentId:string;organizationId:string;loginAlias:string}){const temporaryPassword=generateReadablePassword();const credential_hash=await hashPassword(temporaryPassword);await sql`INSERT INTO student_credentials(student_id,organization_id,login_alias,credential_hash,must_rotate) VALUES(${p.studentId},${p.organizationId},${p.loginAlias},${credential_hash},true) ON CONFLICT(student_id) DO UPDATE SET credential_hash=EXCLUDED.credential_hash,login_alias=EXCLUDED.login_alias,must_rotate=true,last_rotated_at=now()`;return {loginAlias:p.loginAlias,temporaryPassword}}
function generateReadablePassword(){const words=['compass','bright','future','summit','harbor','meadow','planet','rocket','garden','island'];const w=words[randomBytes(1)[0]%words.length];const n=100+(randomBytes(2).readUInt16BE(0)%900);return `${w}-${n}`}
export async function rotateStudentPassword(studentId:string,newPassword:string){if(newPassword.length<8)throw new Error('Password must be at least 8 characters.');const credential_hash=await hashPassword(newPassword);await sql`UPDATE student_credentials SET credential_hash=${credential_hash},must_rotate=false,last_rotated_at=now() WHERE student_id=${studentId}`}
export async function resolveStaffSession(authSubject:string):Promise<Session|null>{const rows=await sql`SELECT p.id,p.display_name,p.preferred_locale,om.organization_id,om.role FROM profiles p LEFT JOIN organization_memberships om ON om.profile_id=p.id AND om.status='active' WHERE p.auth_subject=${authSubject} AND p.status='active' ORDER BY om.joined_at ASC LIMIT 1`;const row=rows[0];if(!row)return null;const role:Role=row.role==='school_admin'||row.role==='owner'?'school_admin':row.role==='teacher'?'teacher':'teacher';return {profileId:row.id,role,organizationId:row.organization_id??null,displayName:row.display_name,locale:row.preferred_locale==='en'?'en':'vi'}}
