-- Integration layer for pluggable LMS, content, assessment, video, SIS and webhook providers.
CREATE TABLE IF NOT EXISTS integration_providers(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),slug text UNIQUE NOT NULL,display_name text NOT NULL,category text NOT NULL,protocol text NOT NULL,description_en text,capabilities text[] NOT NULL DEFAULT '{}',status text NOT NULL DEFAULT 'available',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS integration_installations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),provider_id uuid NOT NULL REFERENCES integration_providers(id) ON DELETE RESTRICT,organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,installed_by uuid REFERENCES profiles(id) ON DELETE SET NULL,display_label text,config jsonb NOT NULL DEFAULT '{}',scopes text[] NOT NULL DEFAULT '{}',status text NOT NULL DEFAULT 'pending',health_state text NOT NULL DEFAULT 'unknown',last_health_at timestamptz,last_error text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,provider_id,display_label));
CREATE TABLE IF NOT EXISTS integration_credentials(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),installation_id uuid NOT NULL REFERENCES integration_installations(id) ON DELETE CASCADE,credential_type text NOT NULL,ciphertext text NOT NULL,key_version int NOT NULL DEFAULT 1,expires_at timestamptz,rotated_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS external_identity_links(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),installation_id uuid NOT NULL REFERENCES integration_installations(id) ON DELETE CASCADE,profile_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,external_user_id text NOT NULL,external_username text,external_role text,linked_at timestamptz NOT NULL DEFAULT now(),UNIQUE(installation_id,external_user_id));
CREATE TABLE IF NOT EXISTS external_object_links(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),installation_id uuid NOT NULL REFERENCES integration_installations(id) ON DELETE CASCADE,internal_type text NOT NULL,internal_id uuid NOT NULL,external_type text,external_id text NOT NULL,sync_direction text NOT NULL DEFAULT 'bidirectional',last_synced_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(installation_id,internal_type,internal_id,external_id));
CREATE TABLE IF NOT EXISTS integration_sync_jobs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),installation_id uuid NOT NULL REFERENCES integration_installations(id) ON DELETE CASCADE,job_type text NOT NULL,direction text NOT NULL DEFAULT 'inbound',status text NOT NULL DEFAULT 'queued',scheduled_at timestamptz NOT NULL DEFAULT now(),started_at timestamptz,finished_at timestamptz,records_total int NOT NULL DEFAULT 0,records_ok int NOT NULL DEFAULT 0,records_failed int NOT NULL DEFAULT 0,error_detail jsonb,triggered_by uuid REFERENCES profiles(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS integration_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),installation_id uuid REFERENCES integration_installations(id) ON DELETE CASCADE,direction text NOT NULL,event_type text NOT NULL,event_key text,payload jsonb NOT NULL DEFAULT '{}',signature_valid boolean,processed_status text NOT NULL DEFAULT 'received',processed_at timestamptz,error_detail text,received_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS integration_audit_log(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid REFERENCES organizations(id) ON DELETE CASCADE,installation_id uuid REFERENCES integration_installations(id) ON DELETE SET NULL,actor_profile_id uuid REFERENCES profiles(id) ON DELETE SET NULL,action text NOT NULL,detail jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
