import { createCipheriv,createDecipheriv,randomBytes } from 'crypto';
import { sql } from '../db';
import { getConnector } from './registry';
function key(){const raw=process.env.INTEGRATION_ENCRYPTION_KEY;if(!raw)throw new Error('INTEGRATION_ENCRYPTION_KEY is not set');const k=Buffer.from(raw,'base64');if(k.length!==32)throw new Error('INTEGRATION_ENCRYPTION_KEY must decode to 32 bytes');return k}
export function encryptSecret(plain:string){const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',key(),iv),enc=Buffer.concat([c.update(plain,'utf8'),c.final()]);return [iv.toString('base64'),c.getAuthTag().toString('base64'),enc.toString('base64')].join('.')}
export function decryptSecret(blob:string){const [iv,tag,data]=blob.split('.'),d=createDecipheriv('aes-256-gcm',key(),Buffer.from(iv,'base64'));d.setAuthTag(Buffer.from(tag,'base64'));return Buffer.concat([d.update(Buffer.from(data,'base64')),d.final()]).toString('utf8')}
export async function loadContext(installationId:string){const rows=await sql`SELECT ii.id,ii.organization_id,ii.config,ip.slug FROM integration_installations ii JOIN integration_providers ip ON ip.id=ii.provider_id WHERE ii.id=${installationId}`;const row=rows[0];if(!row)throw new Error('Installation not found');const creds=await sql`SELECT credential_type,ciphertext FROM integration_credentials WHERE installation_id=${installationId}`;const secrets:Record<string,string>={};for(const c of creds)secrets[c.credential_type]=decryptSecret(c.ciphertext);return {providerSlug:row.slug,ctx:{installationId:row.id,organizationId:row.organization_id,config:row.config??{},secrets}}}
export async function runHealthCheck(installationId:string){const {ctx,providerSlug}=await loadContext(installationId),connector=getConnector(providerSlug);if(!connector)return {ok:false,detail:`No connector registered for ${providerSlug}`};const result=await connector.healthCheck(ctx);await sql`UPDATE integration_installations SET health_state=${result.ok?'healthy':'failing'},last_error=${result.ok?null:(result.detail??'unknown error')},last_health_at=now(),status=CASE WHEN status='pending' AND ${result.ok} THEN 'active' ELSE status END WHERE id=${installationId}`;return result}
export async function dispatchEvent(organizationId:string,type:string,payload:Record<string,unknown>){const installs=await sql`SELECT ii.id,ip.slug FROM integration_installations ii JOIN integration_providers ip ON ip.id=ii.provider_id WHERE ii.organization_id=${organizationId} AND ii.status='active' AND 'analytics_export'=ANY(ip.capabilities)`;for(const inst of installs){const connector=getConnector(inst.slug);if(!connector?.emitEvent)continue;try{const {ctx}=await loadContext(inst.id);await connector.emitEvent(ctx,{type,payload});await sql`INSERT INTO integration_events(installation_id,direction,event_type,payload,processed_status,processed_at) VALUES(${inst.id},'outbound',${type},${JSON.stringify(payload)}::jsonb,'processed',now())`}catch(e){await sql`INSERT INTO integration_events(installation_id,direction,event_type,payload,processed_status,error_detail) VALUES(${inst.id},'outbound',${type},${JSON.stringify(payload)}::jsonb,'failed',${(e as Error).message})`}}}
